apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: tweet-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: razyal/myapp:v1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"  
            cpu: "250m" 
          limits:
            memory: "512Mi"
            cpu: "500m" 
