apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: tweet-project
spec:
  selector:
    app: myapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
