apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  username: YWRtaW4=   # base64 encoded username (e.g., admin)
  password: cGFzc3dvcmQ=   # base64 encoded password (e.g., password)